# Generated by Django 3.0.8 on 2020-07-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='change',
            new_name='M_cap',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='pair',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='high',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='low',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='time',
        ),
        migrations.AddField(
            model_name='currency',
            name='price',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='supply',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='volume',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
